#!/usr/bin/env bash

set -e

cd $HOME/workdir

git clone --recursive https://github.com/apache/incubator-mxnet.git apache-mxnet

cd apache-mxnet

git remote remove origin
git remote add upstream git@github.com:apache/incubator-mxnet.git
git remote add origin git@github.com:AlexChalk/incubator-mxnet.git

# # For working on a version (also requires using matching mxnet image in project.clj)
# git checkout 1.5.0 -b my_mxnet
# git submodule update --init --recursive

# # For building from source (not usually necessary for clojure package) (also requires
# # using internal image in project.clj)
# nix-shell $HOME/nix-configs/do/mxnet-shared-build.nix \
#   --command "make -j $(nproc) \
#       USE_OPENCV=1 \
#       USE_LAPACK=1 \
#       USE_GPERFTOOLS=1 \
#       USE_MKLDNN=1 \
#       USE_BLAS=openblas \
#       USE_LAPACK_PATH=$(nix-instantiate --eval -E 'with import <nixpkgs> {}; lib.makeLibraryPath [liblapack]') \
#       USE_GPERFTOOLS_PATH=$(nix-instantiate --eval -E 'with import <nixpkgs> {}; lib.makeLibraryPath [gperftools]')"
#
# cd scala-package
# mvn install
# cd ..

cd contrib/clojure-package

sed -i 's/\[org.apache.mxnet\/mxnet-full_2.11 "INTERNAL"\]/;\[org.apache.mxnet\/mxnet-full_2.11 "INTERNAL"\]/g' project.clj
sed -i 's/;\[org.apache.mxnet\/mxnet-full_2.11-linux-x86_64-cpu "<insert-snapshot-version>"\]/\[org.apache.mxnet\/mxnet-full_2.11-linux-x86_64-cpu "1.6.0-SNAPSHOT"\]/g' project.clj

lein deps
