#!/usr/bin/env bash

set -e

cd $HOME

git clone https://github.com/adc17/dotfiles
git clone https://github.com/adc17/nix-configs

mkdir workdir

# guest ssh keys

$HOME/nix-configs/do/build-symlinks-nixops-server

sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

nix-env -iA nixos.adcPackages

rustup install stable
rustup default stable

nvim -c ':PlugInstall' -c ':q' -c ':q' $HOME/dotfiles/nvim/init.vim
