#!/usr/bin/env bash

git clone https://github.com/adc17/dotfiles
git clone https://github.com/adc17/nix-configs

mkdir workdir
touch workdir/file.txt

source $HOME/dotfiles/build-symlinks-nixops-server

sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \\n  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

nix-env -iA nixos.adcPackages

zpl update --all && zpl self-update

rustup install stable
rustup default stable
