#!/usr/bin/env bash

set -e

$HOME/nixops/result/bin/nixops deploy -d adc-server --allow-reboot

cat remote-setup-channels | nixops ssh -d adc-server adc@adcserver -t
cat remote-setup | nixops ssh -d adc-server adc@adcserver -t

nixops ssh -d adc-server root@adcserver -t 'passwd adc'

echo "Machine setup complete"
