#!/usr/bin/env bash

set -e

date_today=$(date +"%y-%m-%d_%H:%M:%S")
nixops scp -d adc-server adc@adcserver:$HOME/workdir $HOME/workdir_$date_today -r
# $HOME/nixops/result/bin/nixops destroy -d adc-server
