#!/usr/bin/env bash

cd $HOME

sudo ln -s $(which bash) /bin/bash

sudo mv /etc/nixos/configuration.nix /etc/nixos/configuration.nix.old
sudo ln -s $HOME/nix-configs/t440p/configuration.nix /etc/nixos/configuration.nix

mv $HOME/nix-configs/t440p/hardware-configuration.nix $HOME/nix-configs/t440p/hardware-configuration.nix.old
sudo mv /etc/nixos/hardware-configuration.nix $HOME/nix-configs/t440p/hardware-configuration.nix
sudo ln -s $HOME/nix-configs/t440p/hardware-configuration.nix /etc/nixos/hardware-configuration.nix
sudo ln -s $HOME/nix-configs/t440p/sane-extra-config.nix /etc/nixos/sane-extra-config.nix
sudo ln -s $HOME/nix-configs/t440p/suspend.nix /etc/nixos/suspend.nix

git clone git@github.com:b0o/swaynagmode.git
mkdir bin-personal &> /dev/null
ln -s $HOME/swaynagmode/swaynagmode $HOME/bin-personal/swaynagmode

ln -s $HOME/nix-configs/t440p/nixpkgs $HOME/.config

git clone git@github.com:AlexChalk/fonts-private.git $HOME/.local/share/fonts
