#!/usr/bin/env bash

cd $HOME

sudo ln -s $(which bash) /bin/bash

sudo mv /etc/nixos/configuration.nix /etc/nixos/configuration.nix.old
sudo ln -s $HOME/nix-configs/t440p/configuration.nix /etc/nixos/configuration.nix

mv $HOME/nix-configs/t440p/hardware-configuration.nix $HOME/nix-configs/t440p/hardware-configuration.nix.old
sudo mv /etc/nixos/hardware-configuration.nix $HOME/nix-configs/t440p/hardware-configuration.nix
sudo ln -s $HOME/nix-configs/t440p/hardware-configuration.nix /etc/nixos/hardware-configuration.nix

git clone git@github.com:b0o/swaynagmode.git
mkdir bin-personal &> /dev/null
ln -s $HOME/swaynagmode/swaynagmode $HOME/bin-personal/swaynagmode

ln -s $HOME/nix-configs/t440p/nixpkgs $HOME/.config
mkdir -p $HOME/.config/nixpkgs/packages
ln -s $HOME/nix-configs/t440p/user/config.nix $HOME/.config/nixpkgs/config.nix
ln -s $HOME/nix-configs/t440p/user/packages/neovim.nix $HOME/.config/nixpkgs/packages/neovim.nix

git clone git@github.com:adc17/triplicate-private.git $HOME/.local/share/fonts
