#!/usr/bin/env bash

cd $HOME

# ln Bash
sudo ln -s $(which bash) /bin/bash

# Channel setup
sudo nix-channel --add https://github.com/NixOS/nixos-hardware/archive/master.tar.gz nixos-hardware 
sudo nix-channel --update

nix-channel --add https://nixos.org/channels/nixos-21.11 nixos
nix-channel --add https://nixos.org/channels/nixos-unstable nixos-unstable 
nix-channel --update

# Backup default system configs, link version-controlled configs

# Backup existing system config
sudo mv /etc/nixos/configuration.nix /etc/nixos/configuration.nix.old
# Backup version controlled hardware config
mv $HOME/nix-configs/t440p/etc/nixos/hardware-configuration.nix $HOME/nix-configs/t440p/etc/nixos/hardware-configuration.nix.old
# Version control new hardware config
sudo mv /etc/nixos/hardware-configuration.nix $HOME/nix-configs/t440p/etc/nixos/hardware-configuration.nix

# Add version-controlled system config
sudo ln -s $HOME/nix-configs/t440p/etc/nixos/* /etc/nixos

# Add version-controlled user config
mkdir -p $HOME/.config/nixpkgs
ln -s $HOME/nix-configs/t440p/nixpkgs/config.nix $HOME/.config/nixpkgs
ln -s $HOME/nix-configs/t440p/nixpkgs/overlays.nix $HOME/.config/nixpkgs

# Ssh
# ssh-keygen -t ed25519 -C "contact@alexchalk.net"
# eval "$(ssh-agent -s)"
# ssh-add $HOME/.ssh/id_ed25519

# Fonts
git clone git@github.com:AlexChalk/fonts-private.git $HOME/.local/share/fonts

# Swaynagmode
git clone git@github.com:b0o/swaynagmode.git
mkdir bin-personal &> /dev/null
ln -s $HOME/swaynagmode/swaynagmode $HOME/bin-personal/swaynagmode

# Vim Plug
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
